services:
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    networks:
      - internal-services
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
  prometheus:
    image: "prom/prometheus"
    ports:
      - 9090:9090
    networks:
      - internal-services
    volumes:
      - type: bind
        source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
      - "9096:9096"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - type: bind
        source: loki-config.yaml
        target: /etc/loki/local-config.yaml
        read_only: true
    networks:
      - internal-services
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: grafana
        target: /var/lib/grafana
    networks:
      - internal-services
    depends_on:
      - prometheus
      - loki

networks:
  internal-services:
