{
 "title": "ToDoApp",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Http requests - ToDoApps",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_duration_ms_sum{job=\"ToDoApps\"}[$__rate_interval])",
     "legendFormat": "{{http_status_code}} - {{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "HTTP requests ToDoBackend requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_duration_ms_sum{job=\"ToDoBackend\"}[$__rate_interval])",
     "legendFormat": "{{http_status_code}} - {{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "ToDoApp logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"ToDoAppPremium\"} |= ``"
    }
   ]
  },
  {
   "title": "ToDoBackend logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"ToDoBackend\"} |= ``"
    }
   ]
  }
 ]
}