global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: ToDoApps
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: /metrics
    static_configs:
      - targets: [host.docker.internal:7141]
  - job_name: ToDoBackend
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: /metrics
    static_configs:
      - targets:
          - "host.docker.internal:7141"
